### ISSUE TITLE
why reject hw section?

### ISSUE THREAD

**Issue by blackout314** [Kikobeats/awesome-github#10]

**Comment by ghost** [comment]
Hi! That's because the two links you added are not related to GitHub. This list is for things that have to do with GitHub, like a GitHub OS X client written in Objective-C, or a GitHub issue viewer Chrome extension, etc.

The Arduino links would be great for other lists though:
- https://github.com/krescruz/awesome-arduino

**Comment by Kikobeats** [comment]
exactly! was my fault merge the PR without see the links before, I'm sorry
